version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2024-07-04T14-25-45Z
    restart: always
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  app:
    build: .                     # Собираем образ из Dockerfile в текущей папке
    container_name: minio_test   # Имя контейнера
    depends_on:
      - minio                    # Гарантирует, что MinIO запустится раньше
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: ["python", "main.py"]  # Точка входа